mysql:
  userName: user
  password: password
  host: 127.0.0.1
  port: 3307
  dbName: shortURL
# 以下是Docker app中的配置
#mysql:
#  userName: user
#  password: password
#  host: mysql
#  port: 3307
#  dbName: shortURL

